### ISSUE TITLE
importRawData, apart from importFromFile

### ISSUE THREAD

**Issue by reksc** [popphp/pop-pdf#1]
Hi,

I have a use-case where a PDF document is generated via external web service and therefore I have to put the response data into a file and store it in a tmp directory to be imported into your library.

It would be cool to pass the data directly.

What do you think?

**Comment by nicksagona** [comment]
I think that's an interesting idea. I'm actually in the middle up refactoring/upgrading a number of Pop components and the PDF one will be getting a few tweaks. I'll look to add this to the list. Thanks. I'll keep you posted on it.

**Comment by nicksagona** [comment]
Hey - I apologize for the delay in getting back around to this, but if you check out v3.0.2 that I just pushed up, you'll find a new "importRawData()" method in the Pdf class that will let you know import from a raw data stream. Let me know if that works out for you. Thanks.
