### ISSUE TITLE
Not compatible with PHP 7.2.5

### ISSUE THREAD

**Issue by still-dreaming-1** [popphp/pop-pdf#2]
PHP 7.2.5 fails to run or even lint the code. Example:
`php -l ./vendor/popphp/pop-pdf/src/Build/Compiler.php` produces this error: `PHP Fatal error:  Cannot use Pop\Pdf\Build\Object as Object because 'Object' is a special class name in ./vendor/popphp/pop-pdf/src/Build/Compiler.php on line 17`

**Comment by still-dreaming-1** [comment]
Basically classes and namespaces can't be named Object, unless you don't refer to it directly as such. So you can either rename that directory/namespace to not end with /Object, or you can only use a longer version of the namespace name in all places.

**Comment by nicksagona** [comment]
Right - haven't had a chance to test pop-pdf with 7.2 yet. Should be a relatively easy patch. I'll take a look at it.

**Comment by still-dreaming-1** [comment]
I can submit a pull request if you want? I could just replace all the references to that namespace with a fully qualified name?

**Comment by nicksagona** [comment]
Not really really necessary at this point. Already doing the swap and replace right now. :)

**Comment by nicksagona** [comment]
Alright - I just pushed up a new release - 3.1.0 - with the refactored namespace (Build\Object => Build\PdfObject) Check it out and let me know if that solves the issue for you. Thanks.

**Comment by still-dreaming-1** [comment]
Awesome! I just loaded that from packagist via composer, and that did fix the issue in the one place I was seeing it. I can't yet confirm that it fully works, but I'm not seeing that error. I will create a new issue if I find any other problems. Thank you!

**Comment by still-dreaming-1** [comment]
I successfully generated a very simple PDF file, so it seems to be working. Thanks again.

**Comment by nicksagona** [comment]
Great - thanks for the contribution!
