### ISSUE TITLE
Feature reqest: Align right option when adding text to a page

### ISSUE THREAD

**Issue by still-dreaming-1** [popphp/pop-pdf#3]
I like the way this PDF library is simple to use because it is focused on telling it what text, shapes, and images to draw. But it can be difficult to make text right aligned without an option for this. I guess the difference would be the `$x` provided to `Page->addText()`, would specify the right ending point instead of the left starting point...

**Comment by nicksagona** [comment]
That's something that's most likely possible with some of the recent features added this component recently (namely the method calculating string width.) I would just have to spend time figuring it out and tying it all together. Prob could have a method like $page->addTextRight() or something like that and use the $x as the right ending point like you suggested.

**Comment by still-dreaming-1** [comment]
Ooh that works! In our wrapper class, I used the `Font->getStringWidth()` method to get the width and then just subtracted that from the right X and passed that value into `Page->addText()` as the `$x`. I can't say that would handle all the edge cases in this library code, but it is working for our purposes so far.

**Comment by nicksagona** [comment]
Yep - that's pretty much along the lines of what I was thinking. I'll prob implement something like that in a standalone method like "addTextRight()" or something when I have the time.

**Comment by nicksagona** [comment]
Closing this issue as the latest version released in Feb added improved alignment features and functionality.
